/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search/vector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 3 — Vector search: Nomic embeddings + pgvector cosine distance */
        post: operations["PISearchApiEndpointsSearchVectorVectorSearchEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 1 — Structured search: exact SQL filters, no ranking */
        post: operations["PISearchApiEndpointsSearchStructuredStructuredSearchEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/ontology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 — Ontology: SKOS concepts, synonym expansion, classification and domain rules */
        post: operations["PISearchApiEndpointsSearchOntologyOntologySearchEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/keyword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 2 — Keyword search: Postgres full-text search, BM25-style ranking */
        post: operations["PISearchApiEndpointsSearchKeywordKeywordSearchEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/hybrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 4 — Hybrid search: keyword + vector fused with Reciprocal Rank Fusion */
        post: operations["PISearchApiEndpointsSearchHybridHybridSearchEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products that can be a target device */
        get: operations["PISearchApiEndpointsDemoDemoDevicesEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Golden queries: talk moments with per-stage expectations */
        get: operations["PISearchApiEndpointsDemoGoldenQueriesEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The product category tree (SKOS taxonomy) */
        get: operations["PISearchApiEndpointsDemoTaxonomyEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Allowed spec values (SKOS value vocabularies) */
        get: operations["PISearchApiEndpointsDemoVocabulariesEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CandidateSignals: {
            structuredMatch?: null | boolean;
            /** Format: int32 */
            keywordRank?: null | number;
            /** Format: double */
            keywordScore?: null | number;
            /** Format: int32 */
            vectorRank?: null | number;
            /** Format: double */
            vectorDistance?: null | number;
            /** Format: int32 */
            fusedRank?: null | number;
            conceptMatch?: null | components["schemas"]["ConceptMatch"];
        };
        CompatibilityResult: {
            status: components["schemas"]["CompatibilityStatus"];
            reasons: string[];
        };
        /** @enum {unknown} */
        CompatibilityStatus: "NotEvaluated" | "Compatible" | "Incompatible" | "Unknown";
        /** @enum {unknown} */
        ConceptMatch: "InConcept" | "OutOfConcept" | "NoConcept" | null;
        DebugTrace: {
            steps: components["schemas"]["TraceStep"][];
        };
        DemoDevice: {
            id: string;
            name: string;
            brand: string;
            categories: string[];
        };
        GoldenQuery: {
            id: string;
            title: string;
            moment: string;
            request: components["schemas"]["GoldenQueryRequest"];
            expectations: {
                [key: string]: components["schemas"]["GoldenQueryExpectation"][];
            };
        };
        GoldenQueryContext: {
            targetProductId: null | string;
        };
        GoldenQueryExpectation: {
            productId: string;
            rank: null | components["schemas"]["RankBound"];
            /** Format: int32 */
            absentFromTop: null | number;
            present: null | boolean;
            compatibility: null | string;
            conceptMatch: null | string;
            keywordRank: null | components["schemas"]["RankBound"];
        };
        GoldenQueryFilters: {
            brand: null | string;
            /** Format: double */
            maxPrice: null | number;
            specs: null | Record<string, unknown>;
        };
        GoldenQueryRequest: {
            query: string;
            filters: null | components["schemas"]["GoldenQueryFilters"];
            context: null | components["schemas"]["GoldenQueryContext"];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        ProductResult: {
            id: string;
            name: string;
            brand: string;
            categories: string[];
            /** Format: double */
            price: number;
            specs: Record<string, unknown>;
            /** Format: double */
            score?: null | number;
            signals: components["schemas"]["CandidateSignals"];
            compatibility: components["schemas"]["CompatibilityResult"];
        };
        RankBound: {
            /** Format: int32 */
            min: null | number;
            /** Format: int32 */
            max: null | number;
        };
        SearchContext: {
            targetProductId?: null | string;
        };
        SearchFilters: {
            brand?: null | string;
            categories?: null | string[];
            /** Format: double */
            minPrice?: null | number;
            /** Format: double */
            maxPrice?: null | number;
            specs?: null | Record<string, unknown>;
        };
        SearchOptions: {
            /** Format: int32 */
            candidateDepth?: number;
            /** Format: int32 */
            rrfK?: number;
            /** Format: double */
            keywordWeight?: number;
            /** Format: double */
            vectorWeight?: number;
            expandSynonyms?: boolean;
            applyConstraints?: boolean;
            audience?: string;
            applyPedagogy?: boolean;
            explain?: boolean;
        };
        SearchRequest: {
            query?: string;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            filters?: components["schemas"]["SearchFilters"];
            context?: components["schemas"]["SearchContext"];
            options?: components["schemas"]["SearchOptions"];
        };
        SearchResponse: {
            stage: string;
            query: string;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalResults: number;
            /** Format: double */
            executionTimeMs: number;
            results: components["schemas"]["ProductResult"][];
            debugTrace: components["schemas"]["DebugTrace"];
        };
        TaxonomyNode: {
            notation: string;
            label: string;
            labels: {
                [key: string]: string;
            };
            altLabels: string[];
            definition?: null | string;
            icon?: null | string;
            isDeviceType: boolean;
            narrower: components["schemas"]["TaxonomyNode"][];
        };
        TraceStep: {
            stage: string;
            title: string;
            /** Format: double */
            durationMs: number;
            sql?: null | string;
            parameters?: null | Record<string, unknown>;
            details?: null | Record<string, unknown>;
            notes?: string[];
        };
        ValidationProblem: {
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            instance: string;
            traceId: string;
            detail: string;
            errors: components["schemas"]["ValidationProblemError"][];
        };
        ValidationProblemError: {
            name: string;
            reason: string;
        };
        ValueVocabulary: {
            notation: string;
            label: string;
            specs: string[];
            values: components["schemas"]["ValueVocabularyEntry"][];
        };
        ValueVocabularyEntry: {
            notation: string;
            label: string;
            labels: {
                [key: string]: string;
            };
            altLabels: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PISearchApiEndpointsSearchVectorVectorSearchEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PISearchApiEndpointsSearchStructuredStructuredSearchEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    PISearchApiEndpointsSearchOntologyOntologySearchEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PISearchApiEndpointsSearchKeywordKeywordSearchEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    PISearchApiEndpointsSearchHybridHybridSearchEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PISearchApiEndpointsDemoDemoDevicesEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoDevice"][];
                };
            };
        };
    };
    PISearchApiEndpointsDemoGoldenQueriesEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldenQuery"][];
                };
            };
        };
    };
    PISearchApiEndpointsDemoTaxonomyEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNode"][];
                };
            };
        };
    };
    PISearchApiEndpointsDemoVocabulariesEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueVocabulary"][];
                };
            };
        };
    };
}
